services:
  skat-back:
    networks:
      - skat-net
    image: skat-back
    build:
      context: ./src
      dockerfile: src/Dockerfile
    ports:
      - "5000:8080"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@skatfreunde.de
    volumes:
      - ./certificates:/https:ro
    depends_on:
      - skat-db
  
  skat-db:
    image: postgres:17
    container_name: skat-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "skat.db"
    networks:
      - skat-net
    ports:
      - "5432:5432"
    volumes:
      - skat-data:/var/lib/postgresql/data

networks:
  skat-net:
    driver: bridge

volumes:
  skat-data: